App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]
  collectionOpearions:
    register:
      method: POST
      path: /users/register
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [user_post]
      openapi_context:
        sumary: Registrar un nuevo usuario
      itemOperations:
        get:
          method: GET